name: yuhsuan_sdk
description: Yuhsuan sdk
version: 0.1.0+2
homepage: https://github.com/nyto9999-flutter/yuhsuan_sdk


environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  local_auth: ^2.1.3
  local_auth_android: ^1.0.17
  local_auth_ios: ^1.0.12
  shared_preferences: ^2.0.17
  rational: ^2.2.2
  decimal: ^2.3.2
  dio: ^5.0.0
  cookie_jar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.2

