name: yuhsuan_sdk
description: Yuhsuan sdk
version: 0.1.0+1


environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  local_auth: ^2.1.3
  local_auth_android: ^1.0.17
  local_auth_ios: ^1.0.12

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^4.0.0
